import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { SheetProvedor } from "@/provedores/sheet-provedor";
import { QueryProvedor } from "@/provedores/query-provedor";
import { Toaster } from "@/components/ui/sonner";
import { ThemePovedor } from "@/provedores/theme-provedor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={inter.className}>
          <ThemePovedor
            attribute="class"
            enableSystem
            disableTransitionOnChange
            defaultTheme="light"
          >
            <QueryProvedor>
              {children}
              <Toaster />
              <SheetProvedor />
            </QueryProvedor>
          </ThemePovedor>
        </body>
      </html>
    </ClerkProvider>
  );
}
