import { IconType } from "react-icons/lib";
import { CiCalendar } from "react-icons/ci";
import { IoStatsChartSharp } from "react-icons/io5";
import { LuMonitorSmartphone } from "react-icons/lu";
import { CgGym } from "react-icons/cg";
import { FaNutritionix } from "react-icons/fa";
import { GoHome } from "react-icons/go";

export const cartaoSite: {
  icon: IconType;
  title: string;
  description: string;
}[] = [
  {
    icon: CiCalendar,
    title: "Gerencie Treinos e Dietas",
    description:
      "Organize seus treinos e dietas de maneira simples e eficaz. Personalize seu plano de saúde e fitness conforme suas necessidades.",
  },
  {
    icon: IoStatsChartSharp,
    title: "Acompanhe seu Progresso",
    description:
      "Visualize seu progresso ao longo do tempo. Registre suas conquistas e mantenha-se motivado para alcançar seus objetivos.",
  },
  {
    icon: LuMonitorSmartphone,
    title: "Recursos Avançados",
    description:
      "Acesse uma biblioteca completa de exercícios, vídeos e dicas de especialistas. Explore recursos integrados para maximizar seus resultados.",
  },
] as const;

export const sidebarIcones: { icon: IconType; label: string; href: string }[] =
  [
    {
      icon: GoHome,
      label: "Home",
      href: "/home",
    },
    {
      icon: CgGym,
      label: "Treinos",
      href: "/home/treinos",
    },
    {
      icon: FaNutritionix,
      label: "Dietas",
      href: "/home/dietas",
    },
  ] as const;

export const diasDaSemana = [
  "Domingo",
  "Segunda-feira",
  "Terça-feira",
  "Quarta-feira",
  "Quinta-feira",
  "Sexta-feira",
  "Sábado",
] as const;

export const categoriasTreino: string[] = [
  "Peito",
  "Costas",
  "Bíceps",
  "Tríceps",
  "Ombros",
  "Pernas",
  "Abdômen",
  "Glúteos",
  "Panturrilhas",
  "Cardio",
  "Funcional",
  "Flexibilidade",
] as const;

export const tiposExercisio: string[] = [
  "Força",
  "Cardio",
  "Flexibilidade",
] as const;

export const exercicios: { nome: string; tipo: string }[] = [
  // Peito
  { nome: "Supino Reto", tipo: "Peito" },
  { nome: "Supino Inclinado", tipo: "Peito" },
  { nome: "Supino Declinado", tipo: "Peito" },
  { nome: "Crucifixo", tipo: "Peito" },
  { nome: "Flexões", tipo: "Peito" },
  { nome: "Crossover", tipo: "Peito" },
  { nome: "Pullover", tipo: "Peito" },
  { nome: "Peck Deck", tipo: "Peito" },
  { nome: "Abertura com Halteres", tipo: "Peito" },
  { nome: "Pressão com Barra", tipo: "Peito" },
  { nome: "Flexões Declinadas", tipo: "Peito" },
  { nome: "Supino com Halteres", tipo: "Peito" },
  { nome: "Flys de Cabo", tipo: "Peito" },
  { nome: "Flexões com Pegada Fechada", tipo: "Peito" },
  { nome: "Máquina de Peito", tipo: "Peito" },
  { nome: "Flexões de Braços Diamante", tipo: "Peito" },
  { nome: "Flexões em T", tipo: "Peito" },
  { nome: "Flexões com Bola de Medicina", tipo: "Peito" },
  { nome: "Prensa de Perna Inclinada", tipo: "Peito" },
  { nome: "Flexões Explosivas", tipo: "Peito" },
  { nome: "Supino com Halteres no Solo", tipo: "Peito" },
  { nome: "Pullover na Polia", tipo: "Peito" },
  { nome: "Flexões com Peso", tipo: "Peito" },
  { nome: "Supino com Mancuernas en el Suelo", tipo: "Peito" },
  { nome: "Flexões com Peso", tipo: "Peito" },
  { nome: "Supino com Mancuernas en el Suelo", tipo: "Peito" },

  // Costas
  { nome: "Barra Fixa", tipo: "Costas" },
  { nome: "Levantamento Terra", tipo: "Costas" },
  { nome: "Puxada Frontal", tipo: "Costas" },
  { nome: "Remada Curvada", tipo: "Costas" },
  { nome: "Remada Alta", tipo: "Costas" },
  { nome: "Puxada na Polia Alta", tipo: "Costas" },
  { nome: "Puxada na Polia Baixa", tipo: "Costas" },
  { nome: "Remada Unilateral", tipo: "Costas" },
  { nome: "Máquina de Remada", tipo: "Costas" },
  { nome: "Remada Sentada", tipo: "Costas" },
  { nome: "Pulldown", tipo: "Costas" },
  { nome: "Pullover com Halteres", tipo: "Costas" },
  { nome: "Remada com Barra T", tipo: "Costas" },
  { nome: "Puxada na Polia V-Bar", tipo: "Costas" },
  { nome: "Levantamento Terra Romeno", tipo: "Costas" },
  { nome: "Puxada com Triângulo", tipo: "Costas" },
  { nome: "Remada Cavalinho", tipo: "Costas" },
  { nome: "Remada com Halteres", tipo: "Costas" },
  { nome: "Puxada com Barra em T", tipo: "Costas" },
  { nome: "Remada na Polia Baixa", tipo: "Costas" },
  { nome: "Remada em Pé", tipo: "Costas" },
  { nome: "Pullover na Polia", tipo: "Costas" },
  { nome: "Remada Invertida", tipo: "Costas" },
  { nome: "Puxada com Corda", tipo: "Costas" },
  { nome: "Pullover na Polia Alta", tipo: "Costas" },

  // Bíceps
  { nome: "Rosca Direta", tipo: "Bíceps" },
  { nome: "Rosca Alternada", tipo: "Bíceps" },
  { nome: "Rosca Martelo", tipo: "Bíceps" },
  { nome: "Rosca Concentrada", tipo: "Bíceps" },
  { nome: "Rosca Inversa", tipo: "Bíceps" },
  { nome: "Rosca Scott", tipo: "Bíceps" },
  { nome: "Rosca Spider", tipo: "Bíceps" },
  { nome: "Rosca 21", tipo: "Bíceps" },
  { nome: "Rosca com Corda", tipo: "Bíceps" },
  { nome: "Rosca com Barra W", tipo: "Bíceps" },
  { nome: "Rosca Concentrada com Halteres", tipo: "Bíceps" },
  { nome: "Rosca Martelo com Corda", tipo: "Bíceps" },
  { nome: "Rosca Alternada com Halteres", tipo: "Bíceps" },
  { nome: "Rosca Direta na Barra T", tipo: "Bíceps" },
  { nome: "Rosca com Barra Z", tipo: "Bíceps" },
  { nome: "Rosca 21 com Halteres", tipo: "Bíceps" },
  { nome: "Rosca Concentrada na Máquina", tipo: "Bíceps" },
  { nome: "Rosca Inversa com Corda", tipo: "Bíceps" },
  { nome: "Rosca Scott com Halteres", tipo: "Bíceps" },
  { nome: "Rosca Direta com Corda", tipo: "Bíceps" },
  { nome: "Rosca Martelo Invertida", tipo: "Bíceps" },
  { nome: "Rosca Aranha", tipo: "Bíceps" },
  { nome: "Rosca 21 com Barra W", tipo: "Bíceps" },
  { nome: "Rosca Inversa com Barra W", tipo: "Bíceps" },
  { nome: "Rosca Concentrada com Barra W", tipo: "Bíceps" },

  // Tríceps
  { nome: "Tríceps Testa", tipo: "Tríceps" },
  { nome: "Tríceps Francês", tipo: "Tríceps" },
  { nome: "Mergulho no Banco", tipo: "Tríceps" },
  { nome: "Tríceps Corda", tipo: "Tríceps" },
  { nome: "Tríceps Coice", tipo: "Tríceps" },
  { nome: "Tríceps Pulley Invertido", tipo: "Tríceps" },
  { nome: "Tríceps Testa com Halteres", tipo: "Tríceps" },
  { nome: "Tríceps Testa na Máquina", tipo: "Tríceps" },
  { nome: "Tríceps Coice com Halteres", tipo: "Tríceps" },
  { nome: "Tríceps Corda na Máquina", tipo: "Tríceps" },
  { nome: "Tríceps Testa com Corda", tipo: "Tríceps" },
  { nome: "Tríceps Pulley na Máquina", tipo: "Tríceps" },
  { nome: "Tríceps Pulley Invertido Máquina", tipo: "Tríceps" },
  { nome: "Tríceps Testa Polia", tipo: "Tríceps" },
  { nome: "Tríceps Testa Invertida", tipo: "Tríceps" },
  { nome: "Tríceps Testa com Corda Invertida", tipo: "Tríceps" },
  { nome: "Tríceps Coice Máquina", tipo: "Tríceps" },
  { nome: "Tríceps Pulley Invertido Corda", tipo: "Tríceps" },
  { nome: "Tríceps Testa Corda", tipo: "Tríceps" },
  { nome: "Tríceps Máquina Coice", tipo: "Tríceps" },
  { nome: "Tríceps Testa Máquina", tipo: "Tríceps" },
  { nome: "Tríceps Testa Máquina Corda", tipo: "Tríceps" },
  { nome: "Tríceps Corda Invertida", tipo: "Tríceps" },
  { nome: "Tríceps Corda Máquina", tipo: "Tríceps" },
  { nome: "Tríceps Coice Corda", tipo: "Tríceps" },

  // Ombros
  { nome: "Desenvolvimento Militar", tipo: "Ombros" },
  { nome: "Elevação Lateral", tipo: "Ombros" },
  { nome: "Elevação Frontal", tipo: "Ombros" },
  { nome: "Remada Alta", tipo: "Ombros" },
  { nome: "Arnold Press", tipo: "Ombros" },
  { nome: "Encolhimento de Ombros", tipo: "Ombros" },
  { nome: "Elevação Lateral com Halteres", tipo: "Ombros" },
  { nome: "Elevação Frontal com Barra", tipo: "Ombros" },
  { nome: "Desenvolvimento Militar com Halteres", tipo: "Ombros" },
  { nome: "Elevação Lateral com Cabos", tipo: "Ombros" },
  { nome: "Elevação Frontal com Halteres", tipo: "Ombros" },
  { nome: "Remada Alta com Halteres", tipo: "Ombros" },
  { nome: "Desenvolvimento Militar com Barra", tipo: "Ombros" },
  { nome: "Encolhimento de Ombros com Halteres", tipo: "Ombros" },
  { nome: "Arnold Press com Halteres", tipo: "Ombros" },
  { nome: "Elevação Lateral Máquina", tipo: "Ombros" },
  { nome: "Elevação Frontal com Halteres", tipo: "Ombros" },
  { nome: "Desenvolvimento Militar Máquina", tipo: "Ombros" },
  { nome: "Elevação Lateral com Cabos", tipo: "Ombros" },
  { nome: "Elevação Frontal com Halteres", tipo: "Ombros" },
  { nome: "Remada Alta com Halteres", tipo: "Ombros" },
  { nome: "Desenvolvimento Militar com Barra", tipo: "Ombros" },
  { nome: "Encolhimento de Ombros com Halteres", tipo: "Ombros" },
  { nome: "Arnold Press com Halteres", tipo: "Ombros" },
  { nome: "Elevação Lateral Máquina", tipo: "Ombros" },

  // Pernas
  { nome: "Agachamento Livre", tipo: "Pernas" },
  { nome: "Leg Press", tipo: "Pernas" },
  { nome: "Cadeira Extensora", tipo: "Pernas" },
  { nome: "Cadeira Flexora", tipo: "Pernas" },
  { nome: "Agachamento Hack", tipo: "Pernas" },
  { nome: "Panturrilha Sentado", tipo: "Pernas" },
  { nome: "Panturrilha em Pé", tipo: "Pernas" },
  { nome: "Afundo", tipo: "Pernas" },
  { nome: "Agachamento Sumô", tipo: "Pernas" },
  { nome: "Stiff", tipo: "Pernas" },
  { nome: "Agachamento Frontal", tipo: "Pernas" },
  { nome: "Leg Press 45º", tipo: "Pernas" },
  { nome: "Cadeira Adutora", tipo: "Pernas" },
  { nome: "Cadeira Abdutora", tipo: "Pernas" },
  { nome: "Glúteo Máquina", tipo: "Pernas" },
  { nome: "Hip Thrust", tipo: "Pernas" },
  { nome: "Agachamento com Salto", tipo: "Pernas" },
  { nome: "Caminhada com Barra", tipo: "Pernas" },
  { nome: "Agachamento Bulgário", tipo: "Pernas" },
  { nome: "Passada", tipo: "Pernas" },
  { nome: "Agachamento com Peso Corporal", tipo: "Pernas" },
  { nome: "Caminhada de Barra", tipo: "Pernas" },
  { nome: "Agachamento Sumô com Kettlebell", tipo: "Pernas" },
  { nome: "Stiff com Barra", tipo: "Pernas" },
  { nome: "Agachamento com Saltos", tipo: "Pernas" },

  // Abdômen
  { nome: "Prancha", tipo: "Abdômen" },
  { nome: "Abdominal", tipo: "Abdômen" },
  { nome: "Crunch", tipo: "Abdômen" },
  { nome: "Prancha Lateral", tipo: "Abdômen" },
  { nome: "Leg Raise", tipo: "Abdômen" },
  { nome: "Bicicleta Abdominal", tipo: "Abdômen" },
  { nome: "Abdominal Infra", tipo: "Abdômen" },
  { nome: "Abdominal Oblíquo", tipo: "Abdômen" },
  { nome: "Tesoura", tipo: "Abdômen" },
  { nome: "Abdominal com Perna Estendida", tipo: "Abdômen" },
  { nome: "Abdominal Canivete", tipo: "Abdômen" },
  { nome: "V-Up", tipo: "Abdômen" },
  { nome: "Abdominal com Perna Flexionada", tipo: "Abdômen" },
  { nome: "Twist Russo", tipo: "Abdômen" },
  { nome: "Prancha com Elevação de Perna", tipo: "Abdômen" },
  { nome: "Prancha com Rotação", tipo: "Abdômen" },
  { nome: "Abdominal Máquina", tipo: "Abdômen" },
  { nome: "Prancha com Elevação de Braço", tipo: "Abdômen" },
  { nome: "Abdominal com Bola Suíça", tipo: "Abdômen" },
  { nome: "Prancha com Elevação de Perna", tipo: "Abdômen" },
  { nome: "Prancha com Rotação", tipo: "Abdômen" },
  { nome: "Abdominal Máquina", tipo: "Abdômen" },
  { nome: "Prancha com Elevação de Braço", tipo: "Abdômen" },
  { nome: "Abdominal com Bola Suíça", tipo: "Abdômen" },

  // Glúteos
  { nome: "Elevação de Quadril", tipo: "Glúteos" },
  { nome: "Glúteo 4 Apoios", tipo: "Glúteos" },
  { nome: "Agachamento Búlgaro", tipo: "Glúteos" },
  { nome: "Afundo com Apoio", tipo: "Glúteos" },
  { nome: "Stiff com Barra", tipo: "Glúteos" },
  { nome: "Cadeira Abdutora", tipo: "Glúteos" },
  { nome: "Glúteo Kickback", tipo: "Glúteos" },
  { nome: "Elevação de Quadril com Peso", tipo: "Glúteos" },
  { nome: "Agachamento Sumô", tipo: "Glúteos" },
  { nome: "Afundo", tipo: "Glúteos" },
  { nome: "Stiff com Barra", tipo: "Glúteos" },
  { nome: "Cadeira Abdutora", tipo: "Glúteos" },
  { nome: "Glúteo Kickback", tipo: "Glúteos" },
  { nome: "Elevação de Quadril com Peso", tipo: "Glúteos" },
  { nome: "Agachamento Sumô", tipo: "Glúteos" },
  { nome: "Afundo", tipo: "Glúteos" },
  { nome: "Stiff com Barra", tipo: "Glúteos" },
  { nome: "Cadeira Abdutora", tipo: "Glúteos" },
  { nome: "Glúteo Kickback", tipo: "Glúteos" },
  { nome: "Elevação de Quadril com Peso", tipo: "Glúteos" },
  { nome: "Agachamento Sumô", tipo: "Glúteos" },
  { nome: "Afundo", tipo: "Glúteos" },
  { nome: "Stiff com Barra", tipo: "Glúteos" },
  { nome: "Cadeira Abdutora", tipo: "Glúteos" },
  { nome: "Glúteo Kickback", tipo: "Glúteos" },
  { nome: "Elevação de Quadril com Peso", tipo: "Glúteos" },

  // Panturrilhas
  { nome: "Gêmeos Sentado", tipo: "Panturrilhas" },
  { nome: "Gêmeos em Pé", tipo: "Panturrilhas" },
  { nome: "Elevação de Gêmeos", tipo: "Panturrilhas" },
  { nome: "Panturrilha no Smith", tipo: "Panturrilhas" },
  { nome: "Panturrilha no Leg Press", tipo: "Panturrilhas" },
  { nome: "Elevação de Gêmeos em Máquina", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Leg Press", tipo: "Panturrilhas" },
  { nome: "Panturrilha na Plataforma", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Smith", tipo: "Panturrilhas" },
  { nome: "Elevação de Gêmeos com Barra", tipo: "Panturrilhas" },
  { nome: "Panturrilha em Pé com Halteres", tipo: "Panturrilhas" },
  { nome: "Elevação de Gêmeos na Máquina", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Smith", tipo: "Panturrilhas" },
  { nome: "Panturrilha na Plataforma", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Leg Press", tipo: "Panturrilhas" },
  { nome: "Panturrilha na Plataforma", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Smith", tipo: "Panturrilhas" },
  { nome: "Elevação de Gêmeos com Barra", tipo: "Panturrilhas" },
  { nome: "Panturrilha em Pé com Halteres", tipo: "Panturrilhas" },
  { nome: "Elevação de Gêmeos na Máquina", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Smith", tipo: "Panturrilhas" },
  { nome: "Panturrilha na Plataforma", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Leg Press", tipo: "Panturrilhas" },
  { nome: "Panturrilha na Plataforma", tipo: "Panturrilhas" },
  { nome: "Gêmeos no Smith", tipo: "Panturrilhas" },

  // Cardio
  { nome: "Esteira", tipo: "Cardio" },
  { nome: "Ciclismo", tipo: "Cardio" },
  { nome: "Natação", tipo: "Cardio" },
  { nome: "Corrida", tipo: "Cardio" },
  { nome: "Jump", tipo: "Cardio" },
  { nome: "Remo", tipo: "Cardio" },
  { nome: "Bicicleta Ergométrica", tipo: "Cardio" },
  { nome: "Escalador", tipo: "Cardio" },
  { nome: "Elíptico", tipo: "Cardio" },
  { nome: "Boxe", tipo: "Cardio" },
  { nome: "Pular Corda", tipo: "Cardio" },
  { nome: "Dança Aeróbica", tipo: "Cardio" },
  { nome: "Kickboxing", tipo: "Cardio" },
  { nome: "Escalada", tipo: "Cardio" },
  { nome: "Step", tipo: "Cardio" },
  { nome: "Caminhada Rápida", tipo: "Cardio" },
  { nome: "Esqui", tipo: "Cardio" },
  { nome: "Hidroginástica", tipo: "Cardio" },
  { nome: "CrossFit", tipo: "Cardio" },
  { nome: "Zumba", tipo: "Cardio" },
  { nome: "HIIT", tipo: "Cardio" },
  { nome: "Aeróbica Aquática", tipo: "Cardio" },
  { nome: "Ciclismo Indoor", tipo: "Cardio" },
  { nome: "Surf", tipo: "Cardio" },
  { nome: "Ballet Fitness", tipo: "Cardio" },

  // Funcional
  { nome: "Burpee", tipo: "Funcional" },
  { nome: "Prancha com Elevação Alternada", tipo: "Funcional" },
  { nome: "Agachamento Sumô com Peso", tipo: "Funcional" },
  { nome: "Avanço com Salto", tipo: "Funcional" },
  { nome: "Flexão de Braço", tipo: "Funcional" },
  { nome: "Prancha com Elevação de Perna", tipo: "Funcional" },
  { nome: "Salto na Caixa", tipo: "Funcional" },
  { nome: "Corrida com Obstáculos", tipo: "Funcional" },
  { nome: "Puxada na Corda", tipo: "Funcional" },
  { nome: "Escalada de Corda", tipo: "Funcional" },
  { nome: "Salto à Distância", tipo: "Funcional" },
  { nome: "Levantamento de Pneu", tipo: "Funcional" },
  { nome: "Agachamento com Salto", tipo: "Funcional" },
  { nome: "Prancha com Elevação de Perna", tipo: "Funcional" },
  { nome: "Salto na Caixa", tipo: "Funcional" },
  { nome: "Corrida com Obstáculos", tipo: "Funcional" },
  { nome: "Puxada na Corda", tipo: "Funcional" },
  { nome: "Escalada de Corda", tipo: "Funcional" },
  { nome: "Salto à Distância", tipo: "Funcional" },
  { nome: "Levantamento de Pneu", tipo: "Funcional" },
  { nome: "Agachamento com Salto", tipo: "Funcional" },
  { nome: "Flexão de Braço", tipo: "Funcional" },
  { nome: "Prancha com Elevação Alternada", tipo: "Funcional" },
  { nome: "Avanço com Salto", tipo: "Funcional" },

  // Flexibilidade
  { nome: "Alongamento de Pernas", tipo: "Flexibilidade" },
  { nome: "Alongamento de Braços", tipo: "Flexibilidade" },
  { nome: "Torção de Tronco", tipo: "Flexibilidade" },
  { nome: "Flexão de Coluna", tipo: "Flexibilidade" },
  { nome: "Flexão Lateral do Tronco", tipo: "Flexibilidade" },
  { nome: "Postura de Cachorro Olhando para Baixo", tipo: "Flexibilidade" },
  { nome: "Alongamento de Panturrilha", tipo: "Flexibilidade" },
  { nome: "Alongamento de Pernas", tipo: "Flexibilidade" },
  { nome: "Torção de Tronco", tipo: "Flexibilidade" },
  { nome: "Flexão de Coluna", tipo: "Flexibilidade" },
  { nome: "Flexão Lateral do Tronco", tipo: "Flexibilidade" },
  { nome: "Postura de Cachorro Olhando para Baixo", tipo: "Flexibilidade" },
  { nome: "Alongamento de Panturrilha", tipo: "Flexibilidade" },
  { nome: "Alongamento de Braços", tipo: "Flexibilidade" },
  { nome: "Flexão Lateral do Tronco", tipo: "Flexibilidade" },
  { nome: "Postura de Cachorro Olhando para Baixo", tipo: "Flexibilidade" },
  { nome: "Alongamento de Panturrilha", tipo: "Flexibilidade" },
  { nome: "Alongamento de Pernas", tipo: "Flexibilidade" },
  { nome: "Torção de Tronco", tipo: "Flexibilidade" },
  { nome: "Flexão de Coluna", tipo: "Flexibilidade" },
  { nome: "Flexão Lateral do Tronco", tipo: "Flexibilidade" },
  { nome: "Postura de Cachorro Olhando para Baixo", tipo: "Flexibilidade" },
  { nome: "Alongamento de Panturrilha", tipo: "Flexibilidade" },
  { nome: "Alongamento de Braços", tipo: "Flexibilidade" },
  { nome: "Torção de Tronco", tipo: "Flexibilidade" },
  { nome: "Flexão de Coluna", tipo: "Flexibilidade" },
  { nome: "Flexão Lateral do Tronco", tipo: "Flexibilidade" },
  { nome: "Postura de Cachorro Olhando para Baixo", tipo: "Flexibilidade" },
  { nome: "Alongamento de Panturrilha", tipo: "Flexibilidade" },
  { nome: "Alongamento de Braços", tipo: "Flexibilidade" },
  { nome: "Torção de Tronco", tipo: "Flexibilidade" },
  { nome: "Flexão de Coluna", tipo: "Flexibilidade" },
  { nome: "Flexão Lateral do Tronco", tipo: "Flexibilidade" },
  { nome: "Postura de Cachorro Olhando para Baixo", tipo: "Flexibilidade" },
  { nome: "Alongamento de Panturrilha", tipo: "Flexibilidade" },

  // Pilates
  { nome: "The Hundred", tipo: "Pilates" },
  { nome: "Roll Up", tipo: "Pilates" },
  { nome: "Roll Over", tipo: "Pilates" },
  { nome: "One Leg Circle", tipo: "Pilates" },
  { nome: "Rolling Back", tipo: "Pilates" },
  { nome: "One Leg Stretch", tipo: "Pilates" },
  { nome: "Double Leg Stretch", tipo: "Pilates" },
  { nome: "Spine Stretch", tipo: "Pilates" },
  { nome: "Rocker with Open Legs", tipo: "Pilates" },
  { nome: "Corkscrew", tipo: "Pilates" },
  { nome: "Saw", tipo: "Pilates" },
  { nome: "Swan Dive", tipo: "Pilates" },
  { nome: "One Leg Kick", tipo: "Pilates" },
  { nome: "Double Leg Kick", tipo: "Pilates" },
  { nome: "Neck Pull", tipo: "Pilates" },
  { nome: "Scissors", tipo: "Pilates" },
  { nome: "Bicycle", tipo: "Pilates" },
  { nome: "Shoulder Bridge", tipo: "Pilates" },
  { nome: "Spine Twist", tipo: "Pilates" },
  { nome: "Jackknife", tipo: "Pilates" },
  { nome: "Side Kick", tipo: "Pilates" },
  { nome: "Teaser", tipo: "Pilates" },
  { nome: "Horseback", tipo: "Pilates" },
  { nome: "Control Balance", tipo: "Pilates" },
  { nome: "Scissors with Legs", tipo: "Pilates" },
  { nome: "Diamond", tipo: "Pilates" },

  // Yoga
  { nome: "Postura da Criança", tipo: "Yoga" },
  { nome: "Cachorro Olhando para Baixo", tipo: "Yoga" },
  { nome: "Saudação ao Sol", tipo: "Yoga" },
  { nome: "Gato Vaca", tipo: "Yoga" },
  { nome: "Cobra", tipo: "Yoga" },
  { nome: "Triângulo", tipo: "Yoga" },
  { nome: "Postura do Guerreiro I", tipo: "Yoga" },
  { nome: "Postura do Guerreiro II", tipo: "Yoga" },
  { nome: "Chaturanga", tipo: "Yoga" },
  { nome: "Prancha de Braços", tipo: "Yoga" },
  { nome: "Árvore", tipo: "Yoga" },
  { nome: "Ponte", tipo: "Yoga" },
  { nome: "Postura da Pinça", tipo: "Yoga" },
  { nome: "Postura do Pombo", tipo: "Yoga" },
  { nome: "Savasana", tipo: "Yoga" },
  { nome: "Postura do Triângulo Invertido", tipo: "Yoga" },
  { nome: "Flexão para Trás", tipo: "Yoga" },
  { nome: "Borboleta", tipo: "Yoga" },
  { nome: "Vela", tipo: "Yoga" },
  { nome: "Postura do Peixe", tipo: "Yoga" },
  { nome: "Postura do Guerreiro III", tipo: "Yoga" },
  { nome: "Corvo", tipo: "Yoga" },
  { nome: "Postura do Arado", tipo: "Yoga" },
  { nome: "Pose de Rã", tipo: "Yoga" },
  { nome: "Postura do Lótus", tipo: "Yoga" },
  { nome: "Postura do Guerreiro III", tipo: "Yoga" },
  { nome: "Corvo", tipo: "Yoga" },
  { nome: "Postura do Arado", tipo: "Yoga" },
  { nome: "Pose de Rã", tipo: "Yoga" },
  { nome: "Postura do Lótus", tipo: "Yoga" },

  // Outros
  { nome: "Circuito Funcional", tipo: "Outros" },
  { nome: "Treinamento Suspenso", tipo: "Outros" },
  { nome: "GAP", tipo: "Outros" },
  { nome: "Aula Abdominal", tipo: "Outros" },
  { nome: "Aula de Localizada", tipo: "Outros" },
  { nome: "Cross Training", tipo: "Outros" },
  { nome: "Treinamento Intervalado", tipo: "Outros" },
  { nome: "Treino Pré-natal", tipo: "Outros" },
  { nome: "Treino Pós-natal", tipo: "Outros" },
  { nome: "Treino ao Ar Livre", tipo: "Outros" },
  { nome: "Treino em Dupla", tipo: "Outros" },
  { nome: "Treino em Grupo", tipo: "Outros" },
  { nome: "Treino Online", tipo: "Outros" },
  { nome: "Treino em Casa", tipo: "Outros" },
  { nome: "Treino na Academia", tipo: "Outros" },
  { nome: "Treino na Praia", tipo: "Outros" },
  { nome: "Treino no Parque", tipo: "Outros" },
  { nome: "Treino Funcional", tipo: "Outros" },
  { nome: "Treino de Alta Intensidade", tipo: "Outros" },
  { nome: "Treino para Emagrecimento", tipo: "Outros" },
  { nome: "Treino para Hipertrofia", tipo: "Outros" },
  { nome: "Treino para Resistência", tipo: "Outros" },
  { nome: "Treino para Tonificação", tipo: "Outros" },
  { nome: "Treino para Condicionamento", tipo: "Outros" },
  { nome: "Treino para Flexibilidade", tipo: "Outros" },
  { nome: "Treino para Equilíbrio", tipo: "Outros" },
  { nome: "Treino para Coordenação", tipo: "Outros" },
  { nome: "Treino para Agilidade", tipo: "Outros" },
  { nome: "Treino para Estabilidade", tipo: "Outros" },
  { nome: "Treino para Velocidade", tipo: "Outros" },
  { nome: "Treino para Potência", tipo: "Outros" },
  { nome: "Treino para Concentração", tipo: "Outros" },
  { nome: "Treino para Relaxamento", tipo: "Outros" },
  { nome: "Treino para Foco", tipo: "Outros" },
] as const;

export const horarioTreino: string[] = ["Manha", "Tarde", "Noite"] as const;

export const tiposDeDietas: string[] = [
  "Bulking",
  "Cutting",
  "Manutenção",
  "Comum",
  "Dieta Low Carb",
  "Dieta DASH",
  "Dieta Cetogênica",
  "Dieta Dukan",
  "Dieta Mediterrânea",
] as const;
