name: Daily Water Reset

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todos os dias às 18:46 UTC

jobs:
  reset-water:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Make POST request to reset water consumption
        run: |
          echo "Making POST request to reset water consumption..."
          response=$(curl -X POST https://hs-fitness.vercel.app/api/dietas/resetar-agua \
            -H "Authorization: Bearer ${{ secrets.CLERK_SECRET_KEY }}" \
            -w "%{http_code}" -o response.txt -s)
          echo "Response code: $response"
          echo "Response body:"
          cat response.txt
