name: Daily Water Reset

on:
   schedule:
    - cron: '39 18 * * *'  # Executa todos os dias às 18:39 UTC

jobs:
  reset-water:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Make POST request to reset water consumption
        run: |
          curl -X POST https://hs-fitness.vercel.app/api/reset-water \
            -H "Authorization: Bearer ${{ secrets.CLERK_SECRET_KEY }}" \
            -w "%{http_code}" -o response.txt -s | grep -q "^200$"
